global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "app_01"
    static_configs:
      - targets: ["10.0.17.4:8080"]
        labels:
          app: "app"
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["10.0.17.5:9090"]
