version: '3'

networks:
  monitor-net:
    driver: bridge

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - monitor-net